// <auto-generated />
using System;
using DatabaseLayer.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250131115212_updatePersonTable")]
    partial class updatePersonTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseLayer.Entities.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastLoggedInTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PharamcyId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PharamcyId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.AdminLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfLoggedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateOfLoggout")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLogout")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("AdminLogs");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastUpdatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("PharmacyId")
                        .HasColumnType("int");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.CartItem", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("PhProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ItemId");

                    b.HasIndex("CartId");

                    b.HasIndex("PhProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CountryId");

                    b.ToTable("Countrys");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Jordan"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Customer", b =>
                {
                    b.Property<int>("CutomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CutomerId"));

                    b.Property<DateTime>("DateOfRegister")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastLoggedInDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("Latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("Longitude");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("CutomerId");

                    b.HasIndex("PersonId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.CustomerLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfLoggedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateOfLoggout")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLogout")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomersLogs");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.CustomerPharmacyDistance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<decimal>("distance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("customerPharmacyDistances");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.DeliveryFees", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Fees")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Fees");

                    b.Property<decimal>("MaxDistanceKm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinDistanceKm")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryFees");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Fees = 1.00m,
                            MaxDistanceKm = 3.00m,
                            MinDistanceKm = 0.0m
                        },
                        new
                        {
                            Id = 5,
                            Fees = 2.00m,
                            MaxDistanceKm = 20.00m,
                            MinDistanceKm = 3.10m
                        },
                        new
                        {
                            Id = 6,
                            Fees = 3.00m,
                            MaxDistanceKm = 35.00m,
                            MinDistanceKm = 20.10m
                        },
                        new
                        {
                            Id = 7,
                            Fees = 4.00m,
                            MaxDistanceKm = 50.00m,
                            MinDistanceKm = 35.10m
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.EmailVerification", b =>
                {
                    b.Property<int>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificationId"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly>("DateOfCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CONVERT(DATE,GETDATE())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("RefferenceId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("TimeOfCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TIME(0)")
                        .HasDefaultValueSql("CONVERT(TIME,GETDATE())");

                    b.Property<TimeOnly>("TimeOfExpired")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TIME(0)")
                        .HasComputedColumnSql("DATEADD(MINUTE,3,[TimeOfCreated])", true);

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("VerificationId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("EmailVerifications");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Governorate", b =>
                {
                    b.Property<int>("GovernorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GovernorId"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("GovernorId");

                    b.HasIndex("CountryId");

                    b.ToTable("Governorates");

                    b.HasData(
                        new
                        {
                            GovernorId = 1,
                            CountryId = 1,
                            Name = "Amman",
                            NameArabic = "عمان"
                        },
                        new
                        {
                            GovernorId = 2,
                            CountryId = 1,
                            Name = "Zarqa",
                            NameArabic = "الزرقاء"
                        },
                        new
                        {
                            GovernorId = 3,
                            CountryId = 1,
                            Name = "Irbid",
                            NameArabic = "إربد"
                        },
                        new
                        {
                            GovernorId = 4,
                            CountryId = 1,
                            Name = "Ajloun",
                            NameArabic = "عجلون"
                        },
                        new
                        {
                            GovernorId = 5,
                            CountryId = 1,
                            Name = "Jerash",
                            NameArabic = "جرش"
                        },
                        new
                        {
                            GovernorId = 6,
                            CountryId = 1,
                            Name = "Mafraq",
                            NameArabic = "المفرق"
                        },
                        new
                        {
                            GovernorId = 7,
                            CountryId = 1,
                            Name = "Balqa",
                            NameArabic = "البلقاء"
                        },
                        new
                        {
                            GovernorId = 8,
                            CountryId = 1,
                            Name = "Madaba",
                            NameArabic = "مادبا"
                        },
                        new
                        {
                            GovernorId = 9,
                            CountryId = 1,
                            Name = "Karak",
                            NameArabic = "الكرك"
                        },
                        new
                        {
                            GovernorId = 10,
                            CountryId = 1,
                            Name = "Tafilah",
                            NameArabic = "الطفيلة"
                        },
                        new
                        {
                            GovernorId = 11,
                            CountryId = 1,
                            Name = "Ma'an",
                            NameArabic = "معان"
                        },
                        new
                        {
                            GovernorId = 12,
                            CountryId = 1,
                            Name = "Aqaba",
                            NameArabic = "العقبة"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InvoiceId"));

                    b.Property<DateTime?>("DateAndTimeOfPaid")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("InvoiceId");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Manager", b =>
                {
                    b.Property<int>("ManagerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManagerId"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.HasKey("ManagerId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.MedicalCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("MedicalCategory");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.MedicalType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("MedicalTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MedicalTypeNameArabic")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TypeId");

                    b.ToTable("MedicalTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            MedicalTypeName = "Tablet",
                            MedicalTypeNameArabic = "أقراص"
                        },
                        new
                        {
                            TypeId = 2,
                            MedicalTypeName = "Capsule",
                            MedicalTypeNameArabic = "كبسولات"
                        },
                        new
                        {
                            TypeId = 3,
                            MedicalTypeName = "Syrup",
                            MedicalTypeNameArabic = "شراب"
                        },
                        new
                        {
                            TypeId = 4,
                            MedicalTypeName = "Injection",
                            MedicalTypeNameArabic = "حقن"
                        },
                        new
                        {
                            TypeId = 5,
                            MedicalTypeName = "Ointment",
                            MedicalTypeNameArabic = "مرهم"
                        },
                        new
                        {
                            TypeId = 6,
                            MedicalTypeName = "Cream",
                            MedicalTypeNameArabic = "كريم"
                        },
                        new
                        {
                            TypeId = 7,
                            MedicalTypeName = "Gel",
                            MedicalTypeNameArabic = "جل"
                        },
                        new
                        {
                            TypeId = 8,
                            MedicalTypeName = "Drop",
                            MedicalTypeNameArabic = "قطرات"
                        },
                        new
                        {
                            TypeId = 9,
                            MedicalTypeName = "Inhaler",
                            MedicalTypeNameArabic = "بخاخ"
                        },
                        new
                        {
                            TypeId = 10,
                            MedicalTypeName = "Spray",
                            MedicalTypeNameArabic = "رذاذ"
                        },
                        new
                        {
                            TypeId = 11,
                            MedicalTypeName = "Cosmetic",
                            MedicalTypeNameArabic = "تجميل"
                        },
                        new
                        {
                            TypeId = 12,
                            MedicalTypeName = "Patch",
                            MedicalTypeNameArabic = "لاصق"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Meeting", b =>
                {
                    b.Property<int>("MeetingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MeetingId"));

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("JoindAdminId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("MeetingId");

                    b.HasIndex("JoindAdminId");

                    b.HasIndex("RequestId");

                    b.ToTable("Meetings");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.MeetingPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeOfPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("bit");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("PaidAmount");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RequestId");

                    b.ToTable("MeetingPayments");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("CONVERT(DATE, GETDATE())");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Time")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("time")
                        .HasDefaultValueSql("CONVERT(TIME, GETDATE())");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MessageId");

                    b.HasIndex("AdminId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<decimal>("DeliveryFees")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("OrderDateAndTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("OrderStatusId")
                        .HasColumnType("int");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("TotalPrice");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderStatusId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("PhProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Price");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PhProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.OrderPayment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTimeOfPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsRefund")
                        .HasColumnType("bit");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("PaidAmount");

                    b.Property<int>("PaymentMethodeId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentMethodeId");

                    b.ToTable("OrderPayments");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.OrderStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StatusNameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StatusId");

                    b.ToTable("OrderStatuses");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            StatusName = "Successfull sending",
                            StatusNameArabic = "تم الأرسال بنجاح"
                        },
                        new
                        {
                            StatusId = 2,
                            StatusName = "Pending",
                            StatusNameArabic = "انتظار"
                        },
                        new
                        {
                            StatusId = 3,
                            StatusName = "Preparing",
                            StatusNameArabic = "يتم التحضير"
                        },
                        new
                        {
                            StatusId = 4,
                            StatusName = "Delivering",
                            StatusNameArabic = "توصيل"
                        },
                        new
                        {
                            StatusId = 5,
                            StatusName = "Canceled",
                            StatusNameArabic = "ملغاة"
                        },
                        new
                        {
                            StatusId = 6,
                            StatusName = "Not Accepted",
                            StatusNameArabic = "مرفوض"
                        },
                        new
                        {
                            StatusId = 7,
                            StatusName = "Finished",
                            StatusNameArabic = "منتهي"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.PaymentMethode", b =>
                {
                    b.Property<int>("MethodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MethodeId"));

                    b.Property<string>("MethodeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("MethodeId");

                    b.ToTable("PaymentMethodes");

                    b.HasData(
                        new
                        {
                            MethodeId = 1,
                            MethodeName = "Paypal"
                        },
                        new
                        {
                            MethodeId = 2,
                            MethodeName = "MasterCard"
                        },
                        new
                        {
                            MethodeId = 3,
                            MethodeName = "Visa"
                        },
                        new
                        {
                            MethodeId = 4,
                            MethodeName = "On Delivery"
                        },
                        new
                        {
                            MethodeId = 5,
                            MethodeName = "Click"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ProfileImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.PhPramacyProduct", b =>
                {
                    b.Property<int>("PhProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MedicalQuantity")
                        .HasColumnType("int");

                    b.Property<int>("MedicalTypeId")
                        .HasColumnType("int");

                    b.Property<string>("PhDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PharamcyId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,3)")
                        .HasColumnName("Price");

                    b.Property<DateTime>("ProducedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Stoke")
                        .HasColumnType("int");

                    b.Property<int>("SysProductId")
                        .HasColumnType("int");

                    b.HasKey("PhProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MedicalTypeId");

                    b.HasIndex("PharamcyId");

                    b.HasIndex("SysProductId");

                    b.ToTable("PhPramacyProducts");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Pharmacy", b =>
                {
                    b.Property<int>("PharmacyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PharmacyId"));

                    b.Property<string>("About")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArabicName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateOfRegister")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("date")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GovernorateId")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsHasDelivery")
                        .HasColumnType("bit");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("Latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(10,5)")
                        .HasColumnName("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("PINCode")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PhEmail")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("StreetName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("VedioCallPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VedioCallPrice");

                    b.HasKey("PharmacyId");

                    b.HasIndex("CountryId");

                    b.HasIndex("GovernorateId");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.PharmacyCurrency", b =>
                {
                    b.Property<int>("CurrencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CurrencyId"));

                    b.Property<decimal>("CurrentCurrency")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,3)")
                        .HasDefaultValue(0.00m)
                        .HasColumnName("CurrentCurrency");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.HasKey("CurrencyId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("PharmacyCurrencies");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.PharmacyDeliveryLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeliveriedToHere")
                        .HasColumnType("bit");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId");

                    b.HasIndex("PharmacyId");

                    b.ToTable("PharmacyDeliveryLocations");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.RefundRequest", b =>
                {
                    b.Property<int>("RefundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RefundId"));

                    b.Property<string>("AdditionalInformation")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAndTimeOfRequest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("RefferenceId")
                        .HasColumnType("int");

                    b.Property<int>("RefundStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RefundTypeId")
                        .HasColumnType("int");

                    b.HasKey("RefundId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("RefundStatusId");

                    b.HasIndex("RefundTypeId");

                    b.ToTable("RefundRequests");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.RefundStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("RefundStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Successfull sending",
                            NameArabic = "تم الأرسال بنجاح"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pending",
                            NameArabic = "انتظار"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Accepted",
                            NameArabic = "مقبولة"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rejected",
                            NameArabic = "مرفوضة"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.RefundType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TypeId");

                    b.ToTable("RefundTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            Name = "Refund Order"
                        },
                        new
                        {
                            TypeId = 2,
                            Name = "Refund Request"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.RequestMeeting", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("MeetingURL")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("PharmacyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("int");

                    b.HasKey("RequestId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PharmacyId");

                    b.HasIndex("RequestStatusId");

                    b.ToTable("RequestMeetings");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.RequestStatus", b =>
                {
                    b.Property<int>("ReqStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReqStatusId"));

                    b.Property<string>("ReqStatusArabic")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReqStatusName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ReqStatusId");

                    b.ToTable("RequestStatus");

                    b.HasData(
                        new
                        {
                            ReqStatusId = 1,
                            ReqStatusArabic = "تم الأرسال بنجاح",
                            ReqStatusName = "Successfull sending"
                        },
                        new
                        {
                            ReqStatusId = 2,
                            ReqStatusArabic = "انتظار",
                            ReqStatusName = "Pending"
                        },
                        new
                        {
                            ReqStatusId = 3,
                            ReqStatusArabic = "مقبولة",
                            ReqStatusName = "Accepted"
                        },
                        new
                        {
                            ReqStatusId = 4,
                            ReqStatusArabic = "مرفوضة",
                            ReqStatusName = "Not Accepted"
                        },
                        new
                        {
                            ReqStatusId = 5,
                            ReqStatusArabic = "ملغاة",
                            ReqStatusName = "Cancled"
                        },
                        new
                        {
                            ReqStatusId = 6,
                            ReqStatusArabic = "منتهية",
                            ReqStatusName = "Finished"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.SysProduct", b =>
                {
                    b.Property<int>("SysProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SysProductId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("SysProductId");

                    b.ToTable("SysProducts");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Token", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<DateOnly?>("ExpiredDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("GeneratedDateTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GeneratedToken")
                        .IsRequired()
                        .HasMaxLength(350)
                        .HasColumnType("nvarchar(350)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("UserTypeId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("UserTypeId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.UserType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("UserTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TypeId");

                    b.ToTable("UserTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            UserTypeName = "Admin"
                        },
                        new
                        {
                            TypeId = 2,
                            UserTypeName = "Customer"
                        },
                        new
                        {
                            TypeId = 3,
                            UserTypeName = "Manager"
                        });
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Admin", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "pharmacy")
                        .WithMany("Admins")
                        .HasForeignKey("PharamcyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("pharmacy");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.AdminLog", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Admin", "Admin")
                        .WithMany("AdminLogs")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Cart", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.CartItem", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Cart", "Cart")
                        .WithMany("cartItems")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.PhPramacyProduct", "PhPramacyProduct")
                        .WithMany()
                        .HasForeignKey("PhProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("PhPramacyProduct");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Customer", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.CustomerLog", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Customer", "Customer")
                        .WithMany("CustomerLogs")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.CustomerPharmacyDistance", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.EmailVerification", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Governorate", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Country", "country")
                        .WithMany("Governorates")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Invoice", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Order", "Order")
                        .WithMany("Invoices")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Manager", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Meeting", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Admin", "Admin")
                        .WithMany("Meetings")
                        .HasForeignKey("JoindAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.RequestMeeting", "RequestMeeting")
                        .WithMany("Meetings")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("RequestMeeting");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.MeetingPayment", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Customer", "Customer")
                        .WithMany("MeetingPayments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.RequestMeeting", "RequestMeeting")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RequestMeeting");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Message", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Admin", "Admin")
                        .WithMany("Messages")
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DatabaseLayer.Entities.Customer", "Customer")
                        .WithMany("Messages")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "Pharmacy")
                        .WithMany("Messages")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("Customer");

                    b.Navigation("Pharmacy");

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Order", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.OrderStatus", "OrderStatus")
                        .WithMany("Orders")
                        .HasForeignKey("OrderStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "Pharmacy")
                        .WithMany("Orders")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("OrderStatus");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.OrderItem", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.PhPramacyProduct", "PhPramacyProduct")
                        .WithMany("orderItems")
                        .HasForeignKey("PhProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("PhPramacyProduct");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.OrderPayment", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Customer", "Customer")
                        .WithMany("OrderPayments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.PaymentMethode", "PaymentMethode")
                        .WithMany("OrderPayments")
                        .HasForeignKey("PaymentMethodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Order");

                    b.Navigation("PaymentMethode");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.PhPramacyProduct", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.MedicalCategory", "MedicalCategory")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.MedicalType", "MedicalType")
                        .WithMany("phPramacyProducts")
                        .HasForeignKey("MedicalTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "Pharmacy")
                        .WithMany("phPramacyProducts")
                        .HasForeignKey("PharamcyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.SysProduct", "SysProduct")
                        .WithMany("phPramacyProducts")
                        .HasForeignKey("SysProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MedicalCategory");

                    b.Navigation("MedicalType");

                    b.Navigation("Pharmacy");

                    b.Navigation("SysProduct");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Pharmacy", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Country", "country")
                        .WithMany("Pharmacies")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Governorate", "Governorate")
                        .WithMany("Pharmacies")
                        .HasForeignKey("GovernorateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Governorate");

                    b.Navigation("country");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.PharmacyCurrency", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "Pharmacy")
                        .WithMany()
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.PharmacyDeliveryLocation", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.DeliveryFees", "DeliveryFees")
                        .WithMany("PharmacyDeliveryLocations")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "Pharmacy")
                        .WithMany("PharmacyDeliveryLocations")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DeliveryFees");

                    b.Navigation("Pharmacy");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.RefundRequest", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.RefundStatus", "RefundStatus")
                        .WithMany()
                        .HasForeignKey("RefundStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.RefundType", "RefundType")
                        .WithMany()
                        .HasForeignKey("RefundTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("RefundStatus");

                    b.Navigation("RefundType");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.RequestMeeting", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.Customer", "Customer")
                        .WithMany("RequestMeetings")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.Pharmacy", "Pharmacy")
                        .WithMany("RequestMeetings")
                        .HasForeignKey("PharmacyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DatabaseLayer.Entities.RequestStatus", "RequestStatus")
                        .WithMany("RequestMeetings")
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Pharmacy");

                    b.Navigation("RequestStatus");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Token", b =>
                {
                    b.HasOne("DatabaseLayer.Entities.UserType", "UserType")
                        .WithMany()
                        .HasForeignKey("UserTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserType");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Admin", b =>
                {
                    b.Navigation("AdminLogs");

                    b.Navigation("Meetings");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Cart", b =>
                {
                    b.Navigation("cartItems");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Country", b =>
                {
                    b.Navigation("Governorates");

                    b.Navigation("Pharmacies");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Customer", b =>
                {
                    b.Navigation("CustomerLogs");

                    b.Navigation("MeetingPayments");

                    b.Navigation("Messages");

                    b.Navigation("OrderPayments");

                    b.Navigation("Orders");

                    b.Navigation("RequestMeetings");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.DeliveryFees", b =>
                {
                    b.Navigation("PharmacyDeliveryLocations");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Governorate", b =>
                {
                    b.Navigation("Pharmacies");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.MedicalCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.MedicalType", b =>
                {
                    b.Navigation("phPramacyProducts");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Order", b =>
                {
                    b.Navigation("Invoices");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.OrderStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.PaymentMethode", b =>
                {
                    b.Navigation("OrderPayments");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.PhPramacyProduct", b =>
                {
                    b.Navigation("orderItems");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.Pharmacy", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Messages");

                    b.Navigation("Orders");

                    b.Navigation("PharmacyDeliveryLocations");

                    b.Navigation("RequestMeetings");

                    b.Navigation("phPramacyProducts");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.RequestMeeting", b =>
                {
                    b.Navigation("Meetings");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.RequestStatus", b =>
                {
                    b.Navigation("RequestMeetings");
                });

            modelBuilder.Entity("DatabaseLayer.Entities.SysProduct", b =>
                {
                    b.Navigation("phPramacyProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
